# Site settings
title: Dougherty Squadron
email: cvg3290@rit.edu
url: http://dougherty.rocks
description: "The Dougherty Squadron from RIT is interested running for AAS National Staff for the 2015-2016 term. Vote us to soar to new horizons."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cc9900 #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Col Andrew J. Dougherty Squadron
  location: RIT
  social: Like us on Facebook
  credits: Detachment 538

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/doughertysquadron

# Postal address (add as many lines as necessary)
address:
  - line: rit.edu

# Credits content
credits: 'Visit us at www.rit.edu/afrotc'

# Build settings
markdown: kramdown
permalink: pretty
